### ISSUE TITLE
this.showGreeting is undefined

### ISSUE THREAD

**Issue by alterhu2020** [JetBrains/webstorm-samples#1]
Hi,
I use this repo project for debugging Vue project, but when run in webstorm, intellj idea had stopped in the breakpoint, but the variable is undefined . see below screenshot.

![image](https://user-images.githubusercontent.com/5029046/45462747-a7bdfe00-b73b-11e8-822c-fc227b1679cb.png)

- Idea Version:  IntellJ IDEA 2018.2

any idea for this issue, how can i make the debugger feature work in webstorm? thanks.

**Comment by prigara** [comment]
Hello @alterhu2020,
thanks for your feedback! There's been an issue with the way WebStorm calculated values for `this`. The fix for your particular problem will land in the next week's WebStorm 2018.3 EAP build that you'll be able to download [here](https://www.jetbrains.com/webstorm/eap).
And here's a more general issue that you can follow: https://youtrack.jetbrains.com/issue/WEB-34822

**Comment by alterhu2020** [comment]
@prigara , thanks for your update, so I need to wait for the next week's EAP build, right ?
Thanks again.

**Comment by prigara** [comment]
> I need to wait for the next week's EAP build, right?
Yes, that's right. It will be available next Wednesday or Thursday.

**Comment by prigara** [comment]
Hey @alterhu2020,
Sorry, we have just realised that the fix that we've promised wasn't enabled by default in the last week's EAP build. But you can enable it yourself by setting the registry option `js.debugger.map.this.by.source.code` to false - to do that, open the Registry dialog via the Find Action (Cmd/Ctrl-Shift-A), search for the option and uncheck the checkbox.

**Comment by alterhu2020** [comment]
Yes, it's been a long time waiting for this fix, also I had not saw this options in IntelliJ IDEA, is this only available in WebStorm? thanks  for your update.

**Comment by prigara** [comment]
You need to type “Registry” in the find action popup, not the option name. 
Yes, it’s available in IJ 2018.3 EAP.

**Comment by alterhu2020** [comment]
thanks @prigara , It works now,  Waiting for your team's next build version... 👍

**Comment by 836056404** [comment]
![image](https://user-images.githubusercontent.com/30099739/53690940-1c9af800-3daf-11e9-99f7-48bca99d91fc.png)
why is undefined？

**Comment by 836056404** [comment]
![image](https://user-images.githubusercontent.com/30099739/53691019-be6f1480-3db0-11e9-9a4f-14235278470a.png)
![image](https://user-images.githubusercontent.com/30099739/53691023-c6c74f80-3db0-11e9-8a97-f1f445a76473.png)
2018.3.5 why this is undefined？
