### ISSUE TITLE
webstrom vue  why  this is undefined？

### ISSUE THREAD

**Issue by 836056404** [JetBrains/webstorm-samples#2]
why is undefined？
![db69f001b20e0efb056f2aa2a1231d3c](https://user-images.githubusercontent.com/30099739/53690955-61bf2a00-3daf-11e9-9220-d8ff099fbbfd.png)

**Comment by prigara** [comment]
Hello, please contact the IDE [https://intellij-support.jetbrains.com/hc/en-us/requests/new technical support] and provide a sample application. Thanks!
